# Generated by Django 5.0.6 on 2024-07-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundzeit', models.DateField(auto_now_add=True)),
                ('gemarkung', models.CharField(max_length=100)),
                ('landkreis', models.CharField(max_length=100)),
                ('fundplatznummer', models.IntegerField(max_length=20, null=True)),
                ('flurname', models.CharField(max_length=100)),
                ('flurstück', models.CharField(max_length=100)),
                ('strasse', models.CharField(max_length=100, null=True)),
                ('hausnummer', models.IntegerField(max_length=5, null=True)),
                ('koordinatensystem', models.CharField(max_length=100, null=True)),
                ('lagezumortskern', models.CharField(max_length=30, null=True)),
                ('lageimgelaende', models.CharField(max_length=30, null=True)),
                ('gelaendenutzung', models.CharField(max_length=30, null=True)),
                ('bodenart', models.CharField(max_length=30, null=True)),
                ('befundart', models.CharField(max_length=30, null=True)),
                ('zeitstellung', models.CharField(max_length=30, null=True)),
                ('kultur', models.CharField(max_length=30, null=True)),
                ('gruppe', models.CharField(max_length=30, null=True)),
                ('auffindungsart', models.CharField(max_length=30, null=True)),
                ('erhaltuungszustand', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
