# Generated by Django 5.0.6 on 2024-07-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundmeldung', '0002_alter_fundmeldung_fundplatznummer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundmeldung',
            name='flur',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='flurstück',
            field=models.IntegerField(null=True),
        ),
    ]
