# Generated by Django 5.0.6 on 2024-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundmeldung', '0003_fundmeldung_flur_alter_fundmeldung_flurstück'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundmeldung',
            name='auffindungsart',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='befundart',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='bodenart',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='erhaltuungszustand',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='flurname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='fundplatznummer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='gelaendenutzung',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='gemarkung',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='gruppe',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='hausnummer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='kultur',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='lageimgelaende',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='lagezumortskern',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='landkreis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='strasse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundmeldung',
            name='zeitstellung',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
