# Generated by Django 5.0.6 on 2024-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundmeldung', '0005_fundmeldung_eckpunkt1_nord_fundmeldung_eckpunkt1_ost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundmeldung',
            name='lagezumortskern_meter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundmeldung',
            name='utm_zone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
