# Generated by Django 5.0.6 on 2024-07-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundmeldung', '0006_fundmeldung_lagezumortskern_meter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundmeldung',
            name='einmessungsart',
        ),
    ]
