# Generated by Django 5.0.6 on 2024-07-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundmeldung', '0011_pfleger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundmeldung',
            old_name='strasse',
            new_name='strassenummer',
        ),
        migrations.RemoveField(
            model_name='fundmeldung',
            name='hausnummer',
        ),
    ]
